version: '3'

services:

  authuser-db:
      container_name: authuser-db
      image: postgres:latest
      environment:
        POSTGRES_DB: authuser-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/postgres
      networks:
        - project-decoder
      ports:
        - "5438:5432"


  authuser:
    build: './authuser'
    container_name: authuser
    depends_on:
      - authuser-db
    networks:
      - project-decoder
    environment:
      - DB_HOST=authuser-db
      - DB_PORT=5437
      - DB_NAME=authuser-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8095:8095

networks:
  project-decoder:
    driver: bridge